const commonActionTypes = {
  // GET_ALL_WHATEVER: "GET_ALL_WHATEVER",
  // GET_ALL_WHATEVER_SUCCESS: "GET_ALL_WHATEVER_SUCCESS",
  // GET_ALL_WHATEVER_FAIL: "GET_ALL_WHATEVER_FAIL",
  SET_SELECTED_COMPANY: "SET_SELECTED_COMPANY",
  EDIT_COMPANY : "EDIT_COMPANY"
};

export default commonActionTypes;
